### PR TITLE
add contributing.md

### PR DESCRIPTION
**Pull request by ryanatkn**
doing one more pass on the text

### CODE REVIEW

**Review by greatbacon — APPROVED** [review]

**Comment by greatbacon** [comment]
@ryanatkn You're just waiting on some art for this right? Would there be a problem with merging this now & putting a card on our board to add the art later when it comes in?

**Comment by ryanatkn** [comment]
Agree, I want to make one more pass on the text and then I'll merge. Have a couple small changes.

**Comment by greatbacon** [comment]
> Agree, I want to make one more pass on the text and then I'll merge. Have a couple small changes.

Cool, the card for art is here for reference: https://github.com/orgs/feltcoop/projects/1#card-58556239

**Comment by ryanatkn** [comment]
I'll make another pass when the art comes in and I'm fresh and art-inspired.

**Pull request merged**
