### PR TITLE
format files in the root directory

### PR DESCRIPTION
**Pull request by ryanatkn**
This adds an additional glob to the default formatter to include some files in the root directory. Which files to target is a bit tricky. Generally speaking, Gro expects everything to be in your `src/` directory, but it's common to have some files in the root directory for various tools, and we want a subset of those to be formatted. We don't want to format things like `package-lock.json` or `package.json` because those are modified directly by npm. Insead of adding a blacklist, I opted to just target TypeScript, JavaScript, and Markdown files. Seems ok?

### CODE REVIEW

**Comment by greatbacon** [comment]
Is it possible there might be other ts, js or md files someone other than us might keep in their root that they don't want formatted? Honestly a code cleaner targeting files outside the src directory feels like unexpected behavior to me. This seems like a potential sharp edge for users, especially considering it targets a different subset of files than it does in the src folder.

**Comment by ryanatkn** [comment]
Good point, I can see how that's surprising behavior. In the Node ecosystem it's common to have `*.config.js` (or ts) files in the root directory, along with the normal README, CHANGELOG, CONTRIBUTING, etc. I personally want those formatted and can't think of any I wouldn't, but it's weird that it omits all other file types. I'm unable to think of examples I _wouldn't_ want formatted but the special casing makes it look wrong.

I noticed this before but just confirmed - prettier and npm are formatting `package.json` and `package-lock.json` identically. So at least for our projects with current behavior, we could use the same set of file extensions. If CI ever breaks because of npm not matching the formatting, we could re-evaluate. How does that sound? `gro format` works consistently on both the root directory and `src/`?

**Comment by greatbacon** [comment]
Alright cool, that works for me.

**Comment by ryanatkn** [comment]
Great alright it now uses the same set of extensions.

**Pull request merged**
